library(psych)
install.packages("nycflights13")
attach(nycflights13 :: flights)
head(nycflights13 ::flights)
summary(distance)
describe(distance)
shanto_pagol=cbind(arr_delay,dep_delay,distance)
summary(shanto_pagol)
describe(shanto_pagol)
